backend:
  name: git-gateway
  branch: main
  repo: conime-id/conime-site # Repository baru Anda

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "News"
    folder: "src/content/news" # Nanti kita perlu sesuaikan struktur ini agar CMS bisa edit file JSON/Markdown
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "news"}
      - {label: "Title (ID)", name: "title_id", widget: "string"}
      - {label: "Title (EN)", name: "title_en", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["Anime", "Film", "Game", "Komik"]}
      
      # Fields khusus untuk kebutuhan layout CoNime
      - {label: "Source Name", name: "source_name", widget: "string", required: false, hint: "Contoh: YouTube, Natalie.mu"}
      - {label: "Source URL", name: "source_url", widget: "string", required: false}
      - {label: "Gallery Images", name: "gallery", widget: "list", required: false, field: {label: "Image", name: "image", widget: "image"}}
      
      - {label: "Body (ID)", name: "body_id", widget: "markdown"}
      - {label: "Body (EN)", name: "body_en", widget: "markdown"}
    
  - name: "opinion"
    label: "Opinion"
    folder: "src/content/opinion"
    create: true
    fields:
       - {label: "Title (ID)", name: "title_id", widget: "string"}
       - {label: "Title (EN)", name: "title_en", widget: "string"}
       - {label: "Body (ID)", name: "body_id", widget: "markdown"}
       - {label: "Body (EN)", name: "body_en", widget: "markdown"}

  - name: "reviews"
    label: "Reviews"
    folder: "src/content/reviews"
    create: true
    fields:
       - {label: "Title (ID)", name: "title_id", widget: "string"}
       - {label: "Title (EN)", name: "title_en", widget: "string"}
       - {label: "Rating", name: "rating", widget: "number", value_type: "float", min: 0, max: 10}
       - {label: "Body (ID)", name: "body_id", widget: "markdown"}
       - {label: "Body (EN)", name: "body_en", widget: "markdown"}
