backend:
  name: git-gateway
  branch: main
  repo: conime-id/conime-site # Repository baru Anda

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "News"
    folder: "src/content/news" # Nanti kita perlu sesuaikan struktur ini agar CMS bisa edit file JSON/Markdown
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "news"}
      - {label: "Title (ID)", name: "title_id", widget: "string"}
      - {label: "Title (EN)", name: "title_en", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["Anime", "Film", "Game", "Komik"]}
      - {label: "Body (ID)", name: "body_id", widget: "markdown"}
      - {label: "Body (EN)", name: "body_en", widget: "markdown"}
    
  - name: "opinion"
    label: "Opinion"
    folder: "src/content/opinion"
    create: true
    fields:
       - {label: "Title (ID)", name: "title_id", widget: "string"}
       - {label: "Title (EN)", name: "title_en", widget: "string"}
       - {label: "Body (ID)", name: "body_id", widget: "markdown"}
